---
title: "German_Region_Life_Expectancy"
author: "Jerimiah Williams"
date: "January 26, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(reshape2)
library(Hmisc)
library(ggplot2)
library(stringi)

```

```{r}
load(file = "data/geda_data.RData")
```


```{r}
#read in the life expectancy table from https://ec.europa.eu/eurostat/data/database?node_code=demo_mlexpec this provides the lifexpectancy for each German state broken down by age, year and gender. 
R_lifeexp <- read_tsv("./Data/demo_r_mlifexp.tsv")
```


```{r}
#initial data set first column is an aggregation of Units (years), Sex (abbreviation), age (years of life, i.e. YR1 equals a 1 year old), and region (assigned NUTS-2 code for each state in Europe)
R_lifeexp <- R_lifeexp %>% separate(colOne , into = c("unit", "sex", "age", "region"), sep = ",")
```

```{r}
#extract only the those sections that are "DE" for Germany
R_LE_DE <- subset(R_lifeexp, grepl("DE", R_lifeexp$region) )
#Further extract only the 3 digit german states according to NUTS-2
R_LE_DE <- subset(R_LE_DE, nchar(region) == 3)
R_LE_DE$age <- substring(R_LE_DE$age, 2)
R_LE_DE$AgeBin <- NA
```


```{r}
#convert all "_GE85" to 85 as these people are all 85 or older
R_LE_DE <- mutate(R_LE_DE, age = ifelse(age == "_GE85", "85", age))
```

```{r}
# convert all values of "_LT1" to 0 as these are people whose age is less than 1 year old
R_LE_DE <- mutate(R_LE_DE, age = ifelse(age == "_LT1", "0", age))                               
```

```{r}
#Convert age to number as this is needed to reassign to age bins
R_LE_DE$age <- as.numeric(R_LE_DE$age)
#Drop all ages below 15 since Robert koch only uses 15 years old and up
R_LE_DE <- subset(R_LE_DE, age > 14)
```

```{r}
#move AgeBin to the front as it is easier to verify other changes this way
R_LE_DE<-R_LE_DE[,c(33, 1:32)]
```


```{r}
#if else to assign ages to bins
R_LE_DE <- mutate(R_LE_DE, AgeBin = ifelse(age >14 & age <20, 1, ifelse(age >19 & age <25, 2, ifelse(age > 24 & age < 30, 3, ifelse(age > 29 & age < 35, 4, ifelse(age >34 & age <40, 5, ifelse(age > 39 & age < 45, 6, ifelse(age > 44 & age < 50, 7, ifelse(age > 49 & age < 55, 8, ifelse(age > 54 & age < 60, 9, ifelse(age > 59 & age < 65, 10, ifelse(age > 64 & age < 70, 11,ifelse(age > 69 & age < 75, 12, ifelse(age > 74 & age < 80, 13,  ifelse(age > 79 & age < 85, 14, 15)))))))))))))))
```

```{r}
#Drop all years except those in which the Robert Koch data covers 2014, 2015
R_LE_DE <- R_LE_DE[,c(1:5, 8:9)]
names(R_LE_DE) <- c("AgeBin", "Unit", "Sex", "Age", "Region", "Y2015", "Y2014")
```

```{r}
#Assign factor numbers the same as they are assigned in the "df_geda_num" dataframe 
R_LE_DE <- mutate(R_LE_DE, Region = ifelse(Region == "DE1", 8, ifelse(Region== "DE2", 9, ifelse(Region == "DE3", 11, ifelse(Region == "DE4", 12, ifelse(Region == "DE5",4,ifelse(Region == "DE6", 2, ifelse(Region == "DE7", 6, ifelse(Region == "DE8", 13, ifelse(Region == "DE9", 3, ifelse(Region == "DEA", 5,ifelse(Region == "DEB", 7, ifelse(Region == "DEC", 10, ifelse(Region == "DED", 14, ifelse(Region == "DEE", 15, ifelse(Region == "DEF", 1, ifelse(Region == "DEG", 16, Region)))))))))))))))))
```

```{r}
#To create other charts it is also easier to reassign territories by their name for easier explanation
R_LE_DEPPT <- mutate(R_LE_DE, Region = ifelse(Region == 8, "BADEN-WÜRTTEMBERG", ifelse(Region== 9, "BAVARIA",  ifelse(Region == 11, "BERLIN",  ifelse(Region == 12, "BRANDENBERG",  ifelse(Region == 4, "BREMEN",ifelse(Region == 2, "HAMBURG",  ifelse(Region ==  6, "HESSEN", ifelse(Region == 13, "MECKLENBERG-VORPOMMERN",  ifelse(Region == 3, "LOWER SAXONY",  ifelse(Region == 5, "NORTH RHINE-WESTPHALIA", ifelse(Region == 7, "RHEINLAND-PALATINATE",  ifelse(Region == 10, "SAARLAND",  ifelse(Region == 14, "SAXONY",  ifelse(Region == 15, "SAXONY-ANHALT",  ifelse(Region == 1,"SCHLESWIG-HOLSTEIN", ifelse(Region == 16, "THURINGIA",  Region)))))))))))))))))
```


```{r}
# The Europa dataset life expectancy columns provide remaining years for each age, therefore to get a total life expectancy we add the current agebin to remaining years. since the Robert Koch data covers a two year period the agebin and remaining years are added for both years.
R_LE_DE$LifeExp.2015 <- R_LE_DE$Age + as.numeric(R_LE_DE$Y2015)
R_LE_DE$LifeExp.2014 <- R_LE_DE$Age + as.numeric(R_LE_DE$Y2014)
R_LE_DE <- R_LE_DE[,c(1:5, 8:9)]
```

```{r}
#transform the dataframe from wide to long (pivot on year)
R_LE_DE <- reshape2::melt(R_LE_DE, id.vars = c("AgeBin", "Unit", "Sex", "Age", "Region"))
names(R_LE_DE) <- c("AgeBin", "Unit", "Sex", "Age", "Region", "Year", "LifeExp")
R_LE_DE$Year <- sub("LifeExp.", "", R_LE_DE$Year) 
```


```{r}
#Convert sex factor to the same factor as "df_geda_num" numbering system, females are 1 males are 2 and total is 3. The three will be dropped later in the process when joined to the original "df_geda_num" to create the new dataframe of "df_geda_LifeExp"
R_LE_DE <- mutate(R_LE_DE, Sex = ifelse(Sex == "F", 2, ifelse(Sex== "M", 1, 3)))
```


```{r}
#create a unique ID column for each row including the agebin(AB)+age bin values + Sex(S) + sex values, etc thru region and year. 
R_LE_DE$JoinFac <- paste("AB", R_LE_DE$AgeBin, "S", R_LE_DE$Sex, "R", R_LE_DE$Region, "Y", R_LE_DE$Year, sep = "")
```

```{r}
#the previous R chunk creates duplicates since the bins are in fact 5 ages each with slightly different life expectancies. Current life expectancy methodologies aggregate the data and provide the mean life expectancy when binned. The following two lines of code create a mean for each bin. 
R_LE_DE <- aggregate(R_LE_DE$LifeExp, list(R_LE_DE$JoinFac), mean)
names(R_LE_DE) <- c("JoinFac", "LifeExp")
```

##Look at if there is a better way to do this as it may be skewing the linear relationship

```{r}
#Robert Koch institute list 90 plus but the available life expectancy groups those above 85 together. This duplicates the rows for 85 year olds and carries it to the next age bin. 
R_LE_DE90 <- R_LE_DE
R_LE_DE90$JF4 <- stri_sub(R_LE_DE90$JoinFac, seq(1, 4,by=4), length=4)
R_LE_DE90$JFRest <- substring(R_LE_DE90$JoinFac, 4)
R_LE_DE90 <- subset(R_LE_DE90, JF4 == "AB15")
R_LE_DE90$JoinFac <- gsub("AB15", "AB16", R_LE_DE90$JoinFac)
R_LE_DE90 <- R_LE_DE90[,1:2]
```

```{r}
#join the duplicated rows for 90 years old to the original life expectancy dataframe
R_LE_DE <- bind_rows(R_LE_DE, R_LE_DE90)
```


```{r}
#duplicate df_geda_num dataframe as df_geda_num2 in order to not manipulate the original dataframe
df_geda_num2 <- df_geda_num
#create unique ID row for "df_geda_num2"
df_geda_num2$JoinFac <- paste("AB", df_geda_num2$age5B, "S", df_geda_num2$sex, "R", df_geda_num2$bula, "Y", df_geda_num2$untj, sep = "")
#bring the unique ID column to the front of the dataframe
df_geda_num2 <- df_geda_num2[,c(270, 1:269)]
```

```{r}
#join the life expectancy table R_LE_DE to the df_geda_num2 dataframe, new dataframe "df_geda_LifeExp" is a duplicate of df_geda_num with life expectancy added
df_geda_LifeExp <- inner_join(df_geda_num2, R_LE_DE, by = c("JoinFac" = "JoinFac" ))

```


```{r}
#drop the unique ID column from the dataframe, 
df_geda_LifeExp <- df_geda_LifeExp[2:271]

```


```{r}
#plot the OLS between Life expectancy and well-being score
GZ_LE_plot <- ggplot(data = df_geda_LifeExp, aes(x = LifeExp, y = as.numeric(GZmehm1))) +
  geom_point() +
  geom_smooth(method = "lm", formula = y~x)
GZ_LE_plot
```


```{r}
#plot relationship between overall satisfaction with life and subjective well-being score
GZ_Sat_plot <- ggplot(data = df_geda_LifeExp, aes(x = as.numeric(LQzufrB10), y = as.numeric(GZmehm1)))+
  geom_point() +
  geom_smooth(method = "lm", formula = y~x)
GZ_Sat_plot
```

```{r}
#plot the relationship between life expectancy and Overall satisfaction with life
LE_Sat_plot <- ggplot(data = df_geda_LifeExp, aes(x = LifeExp, y = as.numeric(LQzufrB10)))+
  geom_point() +
  geom_smooth(method = "lm", formula = y~x)
LE_Sat_plot
```

```{r}
#Trim down dataframe to eliminate forced NA that were resulting from entire dataframe
df_geda_LifeExp2 <- df_geda_LifeExp %>% dplyr::select(c(LifeExp, GZmehm1, age5B, sex))

```


```{r}
score_life_Exp <- lm(LifeExp ~ as.numeric(GZmehm1) * as.numeric(age5B) * as.numeric(sex), df_geda_LifeExp2)
summary(score_life_Exp)
```

```{r}
ggplot(df_geda_LifeExp2, aes(LifeExp, as.numeric(GZmehm1)*as.numeric(age5B)*as.numeric(sex)) ) +
  geom_point() +
  stat_smooth(method = "lm", formula = y ~ x)
```


```{r}
ggplot(df_geda_LifeExp2, aes(LifeExp, as.numeric(GZmehm1)*as.numeric(LQzufrB10)*as.numeric(age5B)*as.numeric(sex)) ) +
  geom_point() +
  stat_smooth(method = "loess", formula = y ~ x)
```




