---
title: "VariableReduction"
author: "Uli Kaulfuss"
date: "30 Dezember 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, rows.print=25)
set.seed(42)


library(foreign)
library(readstata13)
library(dplyr)
library(naniar)
library(glmnet)
require(ggplot2)
require(MASS)
require(Hmisc)
require(reshape2)
library(cluster)
library(VIM)
library(readxl)

```



```{r}
GEDA14_meta <- read_excel("data.doc/GEDA14_Variablenuebersicht.xlsx")
df_meta <- GEDA14_meta %>% dplyr::select(c(variable, varlabel_de, varlabel, Thema_und_Fragebogenausschnitt))

GEDA14_meta <- read_excel("data/GEDA14_Variablenuebersicht.xlsx")

```


```{r}
# GEDA14_Export_num <- read_excel("data/GEDA14.Export.Num.xlsx")
GEDA14_Export_text <- read_excel("data/GEDA14.Export.xlsx")
```


```{r}


df_geda_non_filtered_q <- GEDA14_Export_text %>% dplyr::select(c(
  KHhyp12, # Bluthochdruck: I.d.l.12 Mon.
KHhyp, # Bluthochdruck: Jemals ärztlich diagnostiziert
KHhyp12pB, # Indikator bek. (ärztl. diagn.) Bluthochdruckdruck i.d.l. 12 Mon
KHhypmedC, # Indikator blutdrucksenkende Mittel bei bekannter Hypertonie
KHmyo12, # Herzinfarkt: I.d.l. 12 Mon.
KHkhk12, # Koronare Herzerkrankung/Angina Pectoris: I.d.l.12 Mon.
KHbbmyo12,# Herzinfarkt/chron. Beschw.: I.d.l. 12 Mon.
KHhi12, # Herzinsuffizienz: I.d.l.12 Mon.
KHsa12, # Schlaganfall: I.d.l.12 Mon.
KHbbsa12, # Schlaganfall/ chron. Beschwerden infolge SA: I.d.l.12 Mon.
KHdiabB12, # Diabetes: I.d.l.12 Mon.
KHab12, # Asthma: I.d.l.12 Mon.
KHkarz12, # Krebserkrankung: I.d.l.12 Mon.
KHlip12A, # Erhöhte Blutfette/Chol.: I.d.l.12 Mon.
KHlipA, # Jemals erhöhte Blutfette/Cholesterinw. (Arztdiagnose)
KHlipmedA, # Erhöhtes Cholesterin: Zurzeit Medikamenteneinnahme
KHcb12,# Chronische Bronchitis: I.d.l.12 Mon.
KHulc12,# Magen- oder Zwölffingerdarmgeschwür: I.d.l.12 Mon.
KHced12,# Chronisch entzündliche Darmerkrankung: I.d.l.12 Mon.
KHlz12,# Leberzirrhose: I.d.l.12 Mon.
KHcle12,# Andere chronische Lebererkrankungen: I.d.l.12 Mon.
KHniB12,# Chron. Nierenprobleme: I.d.l.12 Mon.
KHdge12,# Arthrose: I.d.l.12 Mon.
KHra12,# Arthritis: I.d.l.12 Mon.
KHos12,# Osteoporose: I.d.l.12 Mon.
KHalgi112,# Allergien: I.d.l. 12 Mon.
GZmehm1,# Allg. Gesundheitszustand
GZmehm3C,# Chronische Krankheiten
GZmehm2D,# Einschränkung durch Krankheit seit mind. 6 Monaten
GZsubj1,# Achten auf Gesundheit
SHseh1,# Brille oder Kontaktlinsen
SHhoer1,# Hörgerät
BBmyo12,# Chronische Beschwerden nach Herzinfarkt: I.d.l.12 Mon.
BBsa12,# Chronische Beschw. infolge eines Schlaganfalls: I.d.l.12 Mon.
BBdors112,# Beschwerden unterer Rücken: I.d.l.12 Mon.
BBdors212,# Beschwerden Nacken, Halswirbelsäule: I.d.l.12 Mon.
BBblas12B,# Harninkontinenz: I.d.l.12 Mon.
BBschwierig1,# Schwierigk. bei Ausführen o. Hilfe: Essen oder Trinken
BBschwierig2,# Schwierigk. bei Ausführen o. Hilfe: v. Bett/Stuhl erheben od. niederlassen
BBschwierig3,# Schwierigk. bei Ausführen o. Hilfe: An- und Ausziehen
BBschwierig4,# Schwierigk. bei Ausführen o. Hilfe: Toilettenbenutzung
BBschwierig5,# Schwierigk. bei Ausführen o. Hilfe: Baden oder Duschen
BBhh1,# Schwierigk. Ausführen o. Hilfe: Mahlzeiten zubereiten
BBhh2,# Schwierigk. Ausführen o. Hilfe: Das Telefon benutzen
BBhh3,# Schwierigk. Ausführen o. Hilfe: Einkäufe erledigen
BBhh4,# Schwierigk. Ausführen o. Hilfe: Medikamenteneinn. org.
BBhh5,# Schwierigk. Ausführen o. Hilfe: Leichte Hausarbeit erledig.
BBhh6,# Schwierigk. Ausführen o. Hilfe: Gelegentlich schwere Hausarbeit erled.
BBhh7,# Schwierigk. Ausführen o. Hilfe: Org. fin. und alltägl. Verwaltungsangeleg.
BBbehB,# Amtlich anerkannte Behinderung 
UVartverkehr,# Verletzung wg. Unfall i.d.l. 12 Monaten: Verkehrsunfall
UVarthaus,# Verletzung wg. Unfall i.d.l. 12 Monaten: Unfall zu Hause
UVartfreiz,# Verletzung wg. Unfall i.d.l. 12 Monaten: Unfall in der Freizeit
UVarbeit1,# Verletzung Arbeitsunfall: I.d.l. 12 Mon. (kein Wegeunfall)
SEschwA_zz,# Schwanger zur Zeit
LQsf367C,# Stärke Schmerzen i.d.l. 4 Wochen
LQsf368C,# Behinderung in Alltagstätigkeiten durch Schmerzen i.d.l. 4 Wochen
LQzufrB10,# Zufriedenheit: Leben insgesamt
PKdep12,# Depression: I.d.l. 12 Mon.
PKphq1,# Beeintr. i.d.l. 2 Wo.: Wenig Interesse/Freude an Ihren Tätigkeiten
PKphq2,# Beeintr. i.d.l. 2 Wo.: Niedergeschlagenheit, Schwermut/Hoffnungslosigkeit
PKphq3,# Beeintr. i.d.l. 2 Wo.: Schwierigk., ein-/durchzuschlafen od. vermehrter Schlaf
PKphq4,# Beeintr. i.d.l. 2 Wo.: Müdigkeit/Gefühl, k. Energie zu haben
PKphq5,# Beeintr. i.d.l. 2 Wo.: Vermind. Appetit/übermäßiges Bedürfnis zu essen
PKphq6,# Beeintr. i.d.l. 2 Wo.: Schlechte Meinung v. sich; Versagen/Familie zu entt.
PKphq7,# Beeintr. i.d.l. 2 Wo.: Schwierigk., sich zu konzentrieren
PKphq8,# Beeintr. i.d.l. 2 Wo.: Veränderung in Bewegung oder Sprache
SFoslo1C,# Nahestehende Personen
SFoslo2C,# Anteilnahme anderer Personen
SFoslo3A,# Erhalt von Hilfe
SFosloA,# Soziale Unterstützung (Oslo-3 Social Support Scale)
IAhypus,# Letzte Blutdruckmessung
IAcholus,# Letzte Blutfettwertebestimmung
IAdiabus,# Letzte Blutzuckermessung
IAtermin,# Auf Untersuchungstermin gewartet i.d.l. 12 Mon.
IAweg,# Untersuchung verzögert wegen Entfernung i.d.l. 12 Mon.
IAarzt8C,# Besuch Psychologen i.d.l. 12 Mon.
IAkhs,# Stationär im Krankenhaus i.d.l. 12 Mon.
IAkhs_k,# Stationär im Krankenhaus i.d.l. 12 Mon.: Anzahl der Nächte (kat)
IAambC,# Tagespatient im Krankenhaus i.d.l. 12 Mon.
IAambC_k,# Tagespatient im Krankenhaus i.d.l. 12 Mon.: Anzahl der Aufnahmen (top coding 10 oder mehr)
IAther2B,# Besuch Physiotherapeuten i.d.l. 12 Mon
IApflege,# Inanspruchnahme häuslicher Pflegedienst: I.d.l. 12 Mon.
IAkfutyp2B_lz,# Letzter Stuhltest
IAkfutyp4B_lz,# Letzte Darmspiegelung
IAkfutyp7B_lz,# Letzte Mammografie
IAkfutyp5B_lz,# Letzter Gebärmutterhalsabstrich
IAkv1D,# Krankenversicherung in 3 Kat.
IPinfl4,# Letzte Grippeimpfung
IPtet,# Jemals Tetanusimpfung
AMarztB,# Einnahme Medikamente v. Arzt verschrieben i.d.l. 2 Wo
AMfrei,# Einnahme Medikamente nicht v. Arzt verschrieben i.d.l. 2 Wo
AUarbzD_k,# Krankheitsbedingt nicht zur Arbeit: Wochen
KAehispaq1,# Tätigkeiten (Anstrengung)
KAehispaq2,# Bewegung zu Fuß: Tage pro Woche
KAehispaq4,# Bewegung mit Fahrrad: Tage pro Woche
KAehispaq6,# Sport: Tage pro Woche
KAehispaq8,# Aufbau/Kräftigung: Tage pro Woche
KAabka,# Mäßig bis sehr anstrengende arbeitsbez. körp. Aktivität
KAsabka,# Sehr anstrengende arbeitsbezogene körperliche Aktivität
KAtbka_k,# Transportbez. körp. Aktivität in MET/Stunden/Woche (top coding ab 100h)
KAgfka,# Einhalt. aerobe WHO-Bew.empf. (mit Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAgfa,# >= 150 min Ausdaueraktiv.und 2 x/ Woche Aktiv. zur Muskelkräft.(Einhalt. beider WHO-Empf.)
KAgfka1,# Einhalt. aerobe WHO-Bew.empf. (o. Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAgfmk,# WHO-Empf. zur Muskelkräft. (>= 2x/Wo. Aktivit. zur Muskelkräftigung)
KAgka,# Ausreichend körp. aktiv während Arbeit oder Freizeit
KAgka_k,# Gesamtaktivität
ENobstB,# Verzehr von Obst
ENgemB,# Verzehr von Gemüse
AKoft12_k,# Alkohol i.d.l. 12 Mon. in 6 Kat.
AKechi47,# Gefährlicher Alkoholkonsum (ECHI 47; > 20/40 g/Tag)
AKbingeC_k3,# Mind. 1 Mal pro Monat Rauschtrinken
AKrisiko,# Riskanter Alkoholkonsum (>10/20 g/Tag)
RCstat_k2,# Rauchstatus in 3 Kat.
RCpass4,# Rauchen in geschlossenen Räumen
GVasku1,# Verlass auf eig. Fähigkeiten in schwier. Situationen
GVasku2,# Aus eigener Kraft Probleme gut meistern
GVasku3,# I.d.R. anstr. und komplizierte Aufgaben gut lösen
BLpflege2C,# Unterstützung/Pflege anderer Personen
sex,# Geschlecht
age5B,# Alter (5-Jahres-Gruppen)
PAfam1C,# Familienstand
PAfam3,# Zusammenleben in Ehe oder eheähnlicher Gemeinschaft
PAhh_k,# Anzahl Personen im Haushalt (kat.)
PAmarstadefacto,# Zusammenleben in eheähnlicher Gemeinschaft
PAhhnbpersk_0_4,# Anzahl Personen im Haushalt: 0 bis 4 Jahre (top coding 3 oder mehr)
PAhhnbpersk_5_13,# Anzahl Personen im Haushalt: 5 bis 13 Jahre (top coding 3 oder mehr)
PAhhnbpersk_14_15,# Anzahl Personen im Haushalt: 14 bis 15 Jahre (top coding 3 oder mehr)
PAhhnbpersk_16_24,# Anzahl Personen im Haushalt: 16 bis 24 Jahre (top coding 3 oder mehr)
PAhhnbpersk_25_64,# Anzahl Personen im Haushalt: 25 bis 64 Jahre (top coding 3 oder mehr)
PAhhnbpersk_65PLUS,# Anzahl Personen im Haushalt: 65 Jahre und älter (top coding 3 oder mehr)
PAhhtype,# Haushaltstyp
PAhh_act,# Anzahl der Pers. im HH: 16-64 J. und erwerbstätig
PAhh_inact,# Anzahl der Pers. im HH: 16-64 J. und nicht erwerbstätig
PAgroe,# Körpergröße (Selbstangabe) [cm]
PAgewiB,# Körpergewicht (Selbstangabe) [kg]
PAbmiB_k,# BMI-Gruppierung (aus Selbstangabe)
SDaeqeink_k,# Äquivalenzeinkommen (imputiert,kat) [€]
SDses_bild,# SES-Subscore: Bildung/Ausbildung
SDses_ber,# SES-Subscore: Berufl. Stellung
SDses_eink,# SES-Subscore: Einkommen
SDses_score,# SES: Gesamtscore
SDses_q5,# Quintile des SES-Scores
SDses,# Sozioökonomischer Status (SES)
SDhhincomez,# Monatl. HH-Nettoeinkommen in Quintilen (imputiert)
SDisced11,# ISCED (2011) - Bildungsgruppen
SDhvtypD,# Hauptverdiener im Haushalt
SDerwt0a,# Lebenssituation derzeit
SDmainstat,# Erwerbstätigkeit (EHIS)
SDalo,# Arbeitslos i.d.l. 5 Jahren
MIbirthplace,# Geburtsland (EHIS)
MIcitizen,# Staatsangehörigkeit
untm,# Untersuchungsmonat
untj,# Untersuchungsjahr
ppoint,# Pseudo Sample Point
ktyp4,# Siedlungsstruktureller Kreistyp (BBSR)
bula,# Bundesland
wob# West/Ost/Berlin
)) %>% mutate_all(factor) %>% mutate_all(as.numeric)



```

Little missing information in the survey - non asked questions are coded accordingly (e.g. -97 -> still in text encoded)

```{r}

mice_plot <- aggr(df_geda_non_filtered_q, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(df_geda_non_filtered_q), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```



```{r}

df_geda_non_filtered_q_nonan <- na.omit(df_geda_non_filtered_q)

```


```{r}

df_x <- df_geda_non_filtered_q_nonan %>% dplyr::select(
  -c(
    GZmehm1
  )
)

df_y <- df_geda_non_filtered_q_nonan %>% dplyr::select(
  c(
    GZmehm1
  )
)

df_y_num <- df_y %>% mutate_all(as.numeric)

df_x_num <- df_x %>% mutate_all(as.numeric)

```

```{r}

df_x_num<- as.matrix(as.data.frame(lapply(df_x_num, as.numeric)))
df_y_num<- as.matrix(as.data.frame(lapply(df_y_num, as.numeric)))

fit=glmnet(df_x_num, df_y_num)


```


```{r}

plot(fit, xvar = "lambda", label = TRUE, main="Questions w/o filtered NAs")

```

```{r}
print(fit)
```

```{r}
lambd <- 0.00799
```


```{r}
myCoefs <- coef(fit, s=lambd);
```

```{r}
myResults <- data.frame(
  features = myCoefs@Dimnames[[1]][ which(myCoefs != 0 ) ], #intercept included
  coefs    = myCoefs              [ which(myCoefs != 0 ) ]  #intercept included
)
myResults <- myResults %>% left_join(df_meta, by = c("features" = "variable"))

myResults$absCoefs <- abs(myResults$coefs)
myResults[(order(-myResults$absCoefs)),] %>% dplyr::select(-varlabel_de)
```



```{r}
myResults %>% 
  group_by(Thema_und_Fragebogenausschnitt) %>% 
  count(Thema_und_Fragebogenausschnitt, sort = TRUE)
```


## Stepwise variable selection

```{r}
step(lm(GZmehm1 ~ ., data=df_geda_non_filtered_q_nonan), direction="backward")
```

```{r}
model <- lm(formula = GZmehm1 ~ KHhyp + KHhypmedC + KHkhk12 + KHhi12 + 
    KHsa12 + KHdiabB12 + KHlipA + KHcb12 + KHulc12 + KHced12 + 
    KHcle12 + KHniB12 + KHdge12 + KHra12 + KHos12 + KHalgi112 + 
    GZmehm3C + GZmehm2D + GZsubj1 + BBdors112 + BBdors212 + BBblas12B + 
    BBhh3 + BBhh6 + BBbehB + SEschwA_zz + LQsf367C + LQsf368C + 
    LQzufrB10 + PKdep12 + PKphq1 + PKphq3 + PKphq4 + PKphq6 + 
    PKphq8 + SFoslo1C + SFoslo2C + SFoslo3A + IAhypus + IAdiabus + 
    IAweg + IAkhs + IAkhs_k + IAambC_k + IAther2B + IApflege + 
    IAkfutyp4B_lz + AMarztB + AMfrei + AUarbzD_k + KAehispaq6 + 
    KAsabka + KAgfka1 + KAgfmk + ENgemB + RCstat_k2 + GVasku1 + 
    GVasku2 + sex + age5B + PAhh_k + PAhhnbpersk_0_4 + PAhhnbpersk_25_64 + 
    PAhhnbpersk_65PLUS + PAhhtype + PAhh_act + PAgroe + PAgewiB + 
    PAbmiB_k + SDses_eink + SDses_score + SDisced11 + SDerwt0a + 
    MIcitizen + bula, data = df_geda_non_filtered_q_nonan)


sum_model <- summary(model)$coefficients

library(data.table)
sum_model <- setDT(as.data.frame(sum_model), keep.rownames = TRUE)[]

sum_model <- sum_model %>% left_join(df_meta, by = c("rn" = "variable"))

sum_model[(order(-sum_model$Estimate)),] %>% dplyr::select(-c(`Std. Error`, `t value`))

```

```{r}
nrow(sum_model)
```

```{r}
sum_model %>%
  group_by(Thema_und_Fragebogenausschnitt) %>% 
  count(Thema_und_Fragebogenausschnitt, sort = TRUE)
```


```{r}
nrow(myResults)
```


```{r}
myResults %>% 
  group_by(Thema_und_Fragebogenausschnitt) %>% 
  count(Thema_und_Fragebogenausschnitt, sort = TRUE)
```


```{r}
cols <- sum_model[sum_model$rn != '(Intercept)',]$rn

cols <- append(cols, "GZmehm1")
df_test <- GEDA14_Export_text %>% dplyr::select(cols) %>% mutate_if(is.character, factor)

df_test$GZmehm1 <- ordered(df_test$GZmehm1, c("Sehr schlecht",  "Schlecht", "Mittelmäßig","Gut", "Sehr gut"))

m <- polr(GZmehm1 ~ ., data = df_test, Hess=TRUE)

## view a summary of the model
# summary(m)

```




```{r calculating p-values}

ctable <- coef(summary(m))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)

# (ci <- confint(m))
```

```{r Odds Ratios}
exp(coef(m))
```




























## Do LASSO per topic area

```{r}
GEDA14_meta %>% 
  group_by(Thema_und_Fragebogenausschnitt) %>% 
  count(Thema_und_Fragebogenausschnitt, sort = TRUE)
```


```{r}
topic_area <- 'Soziodemografie (1704)'

rel_columns <- GEDA14_meta[GEDA14_meta$Thema_und_Fragebogenausschnitt == topic_area,]$variable

# append the response variable

rel_columns <- append(rel_columns, "GZmehm1")
rel_columns

```

```{r}
topic_analysis <- GEDA14_Export_num  %>% dplyr::select(one_of(rel_columns))
```

```{r}

mice_plot <- aggr(topic_analysis, col=c('navyblue','yellow'),
                    numbers=TRUE, sortVars=TRUE,
                    labels=names(topic_analysis), cex.axis=.7,
                    gap=3, ylab=c("Missing data","Pattern"))
```

```{r}


topic_analysis <- topic_analysis %>% dplyr::select(
  -c(
    SDalo_mmk,	
    SDalo_k,		
    SDalogz,	
    SDalokh,		
    SDfuehr	,		
    SDbverh	,		
    SDbest_lz	,		
    SDfuehr2,			
    SDbverh2,
    SDjobstat,
    SDft_pt,	
    SDetoed,		
    SDbest
  )
)


```



```{r}

geda_analysis <- na.omit(topic_analysis)

# geda_analysis <- na.omit(GEDA14_Export_text)

```


```{r}

df_x <- geda_analysis %>% dplyr::select(
  -c(
    GZmehm1
  )
)

df_y <- geda_analysis %>% dplyr::select(
  c(
    GZmehm1
  )
)

df_y_num <- df_y %>% mutate_all(as.numeric)

df_x_num <- df_x %>% mutate_all(as.numeric)

```

```{r}

df_x_num<- as.matrix(as.data.frame(lapply(df_x_num, as.numeric)))
df_y_num<- as.matrix(as.data.frame(lapply(df_y_num, as.numeric)))

fit=glmnet(df_x_num, df_y_num)


```


```{r}

plot(fit, xvar = "lambda", label = TRUE, main=topic_area)

```

```{r}
print(fit)
```

```{r}
lambd <- 0.041
```


```{r}
myCoefs <- coef(fit, s=lambd); 

#library(leaps)

# leaps=regsubsets(GZmehm1 ~ .,data=df_analysis_num, nbest=1, really.big=TRUE)
# plot(leaps, scale="r2")
```

```{r}
myResults <- data.frame(
  features = myCoefs@Dimnames[[1]][ which(myCoefs != 0 ) ], #intercept included
  coefs    = myCoefs              [ which(myCoefs != 0 ) ]  #intercept included
)
myResults <- myResults %>% left_join(df_meta, by = c("features" = "variable"))

myResults$absCoefs <- abs(myResults$coefs)
myResults[(order(-myResults$absCoefs)),]
```



```{r}

df_base <- GEDA14_Export_text %>% dplyr::select(
KHhyp12, # Bluthochdruck: I.d.l.12 Mon.
KHhyp, # Bluthochdruck: Jemals ärztlich diagnostiziert
KHhyp12pB, # Indikator bek. (ärztl. diagn.) Bluthochdruckdruck i.d.l. 12 Mon
KHhypmedC, # Indikator blutdrucksenkende Mittel bei bekannter Hypertonie
KHmyo12, # Herzinfarkt: I.d.l. 12 Mon.
KHkhk12, # Koronare Herzerkrankung/Angina Pectoris: I.d.l.12 Mon.
KHbbmyo12, # Herzinfarkt/chron. Beschw.: I.d.l. 12 Mon.
KHhi12, # Herzinsuffizienz: I.d.l.12 Mon.
KHsa12, # Schlaganfall: I.d.l.12 Mon.
KHbbsa12, # Schlaganfall/ chron. Beschwerden infolge SA: I.d.l.12 Mon.
KHdiabB12, # Diabetes: I.d.l.12 Mon.
KHab12, # Asthma: I.d.l.12 Mon.
KHkarz12, # Krebserkrankung: I.d.l.12 Mon.
KHlip12A, # Erhöhte Blutfette/Chol.: I.d.l.12 Mon.
KHlipA, # Jemals erhöhte Blutfette/Cholesterinw. (Arztdiagnose)
KHlipmedA, # Erhöhtes Cholesterin: Zurzeit Medikamenteneinnahme
KHcb12, # Chronische Bronchitis: I.d.l.12 Mon.
KHulc12, # Magen- oder Zwölffingerdarmgeschwür: I.d.l.12 Mon.
KHced12, # Chronisch entzündliche Darmerkrankung: I.d.l.12 Mon.
KHlz12, # Leberzirrhose: I.d.l.12 Mon.
KHcle12, # Andere chronische Lebererkrankungen: I.d.l.12 Mon.
KHniB12, # Chron. Nierenprobleme: I.d.l.12 Mon.
KHdge12, # Arthrose: I.d.l.12 Mon.
KHra12, # Arthritis: I.d.l.12 Mon.
KHos12, # Osteoporose: I.d.l.12 Mon.
KHalgi112, # Allergien: I.d.l. 12 Mon.
GZmehm1, # Allg. Gesundheitszustand
GZmehm3C, # Chronische Krankheiten
GZmehm2D, # Einschränkung durch Krankheit seit mind. 6 Monaten
GZsubj1, # Achten auf Gesundheit
SHseh1, # Brille oder Kontaktlinsen
SHhoer1, # Hörgerät
BBmyo12, # Chronische Beschwerden nach Herzinfarkt: I.d.l.12 Mon.
BBsa12, # Chronische Beschw. infolge eines Schlaganfalls: I.d.l.12 Mon.
BBdors112, # Beschwerden unterer Rücken: I.d.l.12 Mon.
BBdors212, # Beschwerden Nacken, Halswirbelsäule: I.d.l.12 Mon.
BBblas12B, # Harninkontinenz: I.d.l.12 Mon.
BBschwierig1, # Schwierigk. bei Ausführen o. Hilfe: Essen oder Trinken
BBschwierig2, # Schwierigk. bei Ausführen o. Hilfe: v. Bett/Stuhl erheben od. niederlassen
BBschwierig3, # Schwierigk. bei Ausführen o. Hilfe: An- und Ausziehen
BBschwierig4, # Schwierigk. bei Ausführen o. Hilfe: Toilettenbenutzung
BBschwierig5, # Schwierigk. bei Ausführen o. Hilfe: Baden oder Duschen
BBhh1, # Schwierigk. Ausführen o. Hilfe: Mahlzeiten zubereiten
BBhh2, # Schwierigk. Ausführen o. Hilfe: Das Telefon benutzen
BBhh3, # Schwierigk. Ausführen o. Hilfe: Einkäufe erledigen
BBhh4, # Schwierigk. Ausführen o. Hilfe: Medikamenteneinn. org.
BBhh5, # Schwierigk. Ausführen o. Hilfe: Leichte Hausarbeit erledig.
BBhh6, # Schwierigk. Ausführen o. Hilfe: Gelegentlich schwere Hausarbeit erled.
BBhh7, # Schwierigk. Ausführen o. Hilfe: Org. fin. und alltägl. Verwaltungsangeleg.
BBbehB, # Amtlich anerkannte Behinderung 
UVartverkehr, # Verletzung wg. Unfall i.d.l. 12 Monaten: Verkehrsunfall
UVarthaus, # Verletzung wg. Unfall i.d.l. 12 Monaten: Unfall zu Hause
UVartfreiz, # Verletzung wg. Unfall i.d.l. 12 Monaten: Unfall in der Freizeit
UVarbeit1, # Verletzung Arbeitsunfall: I.d.l. 12 Mon. (kein Wegeunfall)
SEschwA_zz, # Schwanger zur Zeit
LQsf367C, # Stärke Schmerzen i.d.l. 4 Wochen
LQsf368C, # Behinderung in Alltagstätigkeiten durch Schmerzen i.d.l. 4 Wochen
LQzufrB10, # Zufriedenheit: Leben insgesamt
PKdep12, # Depression: I.d.l. 12 Mon.
PKphq1, # Beeintr. i.d.l. 2 Wo.: Wenig Interesse/Freude an Ihren Tätigkeiten
PKphq2, # Beeintr. i.d.l. 2 Wo.: Niedergeschlagenheit, Schwermut/Hoffnungslosigkeit
PKphq3, # Beeintr. i.d.l. 2 Wo.: Schwierigk., ein-/durchzuschlafen od. vermehrter Schlaf
PKphq4, # Beeintr. i.d.l. 2 Wo.: Müdigkeit/Gefühl, k. Energie zu haben
PKphq5, # Beeintr. i.d.l. 2 Wo.: Vermind. Appetit/übermäßiges Bedürfnis zu essen
PKphq6, # Beeintr. i.d.l. 2 Wo.: Schlechte Meinung v. sich; Versagen/Familie zu entt.
PKphq7, # Beeintr. i.d.l. 2 Wo.: Schwierigk., sich zu konzentrieren
PKphq8, # Beeintr. i.d.l. 2 Wo.: Veränderung in Bewegung oder Sprache
PKphq8_k1, # PHQ-8: Skalensummenwert Depressive Symptome in 5 Kat.
PKphq8_k2, # PHQ-8: Skalensummenwert Depressive Symptome in 3 Kat.
PKphq8_k3, # PHQ-8: Depressive Symptomatik
PKphq8diag, # PHQ-8: Diagnostische Kat.
SFoslo1C, # Nahestehende Personen
SFoslo2C, # Anteilnahme anderer Personen
SFoslo3A, # Erhalt von Hilfe
SFosloA, # Soziale Unterstützung (Oslo-3 Social Support Scale)
IAhypus, # Letzte Blutdruckmessung
IAcholus, # Letzte Blutfettwertebestimmung
IAdiabus, # Letzte Blutzuckermessung
IAtermin, # Auf Untersuchungstermin gewartet i.d.l. 12 Mon.
IAweg, # Untersuchung verzögert wegen Entfernung i.d.l. 12 Mon.
IAkosten1, # Benötigte US/Behandlung n. bezahlbar i.d.l. 12 Mon.: Ärztl. US/Behandlung
IAkosten2, # Benötigte US/Behandlung n. bezahlbar i.d.l. 12 Mon.: Zahnärztl. US/Behandlung
IAkosten3, # Benötigte US/Behandlung n. bezahlbar i.d.l. 12 Mon.: Verordnete Med.
IAkosten4, # Benötigte US/Behandlung n. bezahlbar i.d.l. 12 Mon.: US/Behandlung psy. Prob.
IAarzt8C, # Besuch Psychologen i.d.l. 12 Mon.
IAkhs, # Stationär im Krankenhaus i.d.l. 12 Mon.
IAkhs_k, # Stationär im Krankenhaus i.d.l. 12 Mon.: Anzahl der Nächte (kat)
IAambC, # Tagespatient im Krankenhaus i.d.l. 12 Mon.
IAambC_k, # Tagespatient im Krankenhaus i.d.l. 12 Mon.: Anzahl der Aufnahmen (top coding 10 oder mehr)
IAther2B, # Besuch Physiotherapeuten i.d.l. 12 Mon
IApflege, # Inanspruchnahme häuslicher Pflegedienst: I.d.l. 12 Mon.
IAkfutyp2B_lz, # Letzter Stuhltest
IAkfutyp4B_lz, # Letzte Darmspiegelung
IAkfutyp7B_lz, # Letzte Mammografie
IAkfutyp5B_lz, # Letzter Gebärmutterhalsabstrich
IAkv1D, # Krankenversicherung in 3 Kat.
IAkv2D, # Krankenversicherung in 4 Kat.
IPinfl4, # Letzte Grippeimpfung
IPtet, # Jemals Tetanusimpfung
AMarztB, # Einnahme Medikamente v. Arzt verschrieben i.d.l. 2 Wo
AMfrei, # Einnahme Medikamente nicht v. Arzt verschrieben i.d.l. 2 Wo
AUarbzD_k, # Krankheitsbedingt nicht zur Arbeit: Wochen
KAehispaq1, # Tätigkeiten (Anstrengung)
KAehispaq2, # Bewegung zu Fuß: Tage pro Woche
KAehispaq4, # Bewegung mit Fahrrad: Tage pro Woche
KAehispaq6, # Sport: Tage pro Woche
KAehispaq8, # Aufbau/Kräftigung: Tage pro Woche
KAabka, # Mäßig bis sehr anstrengende arbeitsbez. körp. Aktivität
KAsabka, # Sehr anstrengende arbeitsbezogene körperliche Aktivität
KAtbka_k, # Transportbez. körp. Aktivität in MET/Stunden/Woche (top coding ab 100h)
KAgfka, # Einhalt. aerobe WHO-Bew.empf. (mit Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAgfa, # >= 150 min Ausdaueraktiv.und 2 x/ Woche Aktiv. zur Muskelkräft.(Einhalt. beider WHO-Empf.)
KAgfka1, # Einhalt. aerobe WHO-Bew.empf. (o. Gehen >= 150 Min. aerobe körp. Aktiv./Wo)
KAgfmk, # WHO-Empf. zur Muskelkräft. (>= 2x/Wo. Aktivit. zur Muskelkräftigung)
KAgka, # Ausreichend körp. aktiv während Arbeit oder Freizeit
KAgka_k, # Gesamtaktivität
ENobstB, # Verzehr von Obst
ENgemB, # Verzehr von Gemüse
AKoft12_k, # Alkohol i.d.l. 12 Mon. in 6 Kat.
AKechi47, # Gefährlicher Alkoholkonsum (ECHI 47; > 20/40 g/Tag)
AKbingeC_k, # Binge-Drinking (>= 6 alk. Getr. bei einer Gelegenheit) in 4 Kat.
AKbingeC_k3, # Mind. 1 Mal pro Monat Rauschtrinken
AKrisiko, # Riskanter Alkoholkonsum (>10/20 g/Tag)
AKrisiko2, # Riskanter Alkoholkonsum (>10/20 g/Tag) 4 Kat.
RCstat, # Rauchen
RCstat_k2, # Rauchstatus in 3 Kat.
RCpass4, # Rauchen in geschlossenen Räumen
GVasku1, # Verlass auf eig. Fähigkeiten in schwier. Situationen
GVasku2, # Aus eigener Kraft Probleme gut meistern
GVasku3, # I.d.R. anstr. und komplizierte Aufgaben gut lösen
BLpflege2C, # Unterstützung/Pflege anderer Personen
sex, # Geschlecht
sexb, # Geschlecht
age5B, # Alter (5-Jahres-Gruppen)
age10B, # Alter (10-Jahres-Gruppen)
agegrp1, # Altersgruppe 1
agegrp2, # Altersgruppe 2
agegrp4, # Altersgruppe 4
agegrp6, # Altersgruppe 6
agegrp7, # Altersgruppe 7
agegrp8, # Altersgruppe 8
agegrp9, # Altersgruppe 9
agegrp10, # Altersgruppe 10
agegrp11, # Altersgruppe 11
agegrp12, # Altersgruppe 12
PAfam1C, # Familienstand
PAfam3, # Zusammenleben in Ehe oder eheähnlicher Gemeinschaft
PAhh_k, # Anzahl Personen im Haushalt (kat.)
PAmarstadefacto, # Zusammenleben in eheähnlicher Gemeinschaft
PAhhnbpersk_0_4, # Anzahl Personen im Haushalt: 0 bis 4 Jahre (top coding 3 oder mehr)
PAhhnbpersk_5_13, # Anzahl Personen im Haushalt: 5 bis 13 Jahre (top coding 3 oder mehr)
PAhhnbpersk_14_15, # Anzahl Personen im Haushalt: 14 bis 15 Jahre (top coding 3 oder mehr)
PAhhnbpersk_16_24, # Anzahl Personen im Haushalt: 16 bis 24 Jahre (top coding 3 oder mehr)
PAhhnbpersk_25_64, # Anzahl Personen im Haushalt: 25 bis 64 Jahre (top coding 3 oder mehr)
PAhhnbpersk_65PLUS, # Anzahl Personen im Haushalt: 65 Jahre und älter (top coding 3 oder mehr)
PAhhtype, # Haushaltstyp
PAbmiB_k, # BMI-Gruppierung (aus Selbstangabe)
PAbmiB_k2, # BMI-Gruppierung detaill. (aus Selbstangabe)
PAueberB, # Übergewicht nach WHO (BMI>=25; aus Selbstangabe)
PAadiposB, # Adipositas nach WHO (BMI>=30; aus Selbstangabe)
SDaeqeink_k, # Äquivalenzeinkommen (imputiert,kat) [€]
SDses_q5, # Quintile des SES-Scores
SDses, # Sozioökonomischer Status (SES)
SDhhincomez, # Monatl. HH-Nettoeinkommen in Quintilen (imputiert)
SDisced11, # ISCED (2011) - Bildungsgruppen
SDisced11z, # ISCED (2011) - Klassifikation, 1stellig
SDhvtypD, # Hauptverdiener im Haushalt
SDerwt0a, # Lebenssituation derzeit
SDmainstat, # Erwerbstätigkeit (EHIS)
SDalo, # Arbeitslos i.d.l. 5 Jahren
MIbirthplace, # Geburtsland (EHIS)
MIcitizen, # Staatsangehörigkeit
ktyp4, # Siedlungsstruktureller Kreistyp (BBSR)
bula, # Bundesland
bula2, # Bundesland (leicht zus.gefasst)
wob, # West/Ost/Berlin
reg5, # Region in 5 Kategorien
reg5b, # Region in 5 Kategorien (Version b)
reg4, # Region in 4 Kategorien
reg6, # Region in 6 Kategorien
reg7, # Region in 7 Kategorien (Nielsen-Gebiete)
ns3 # Nord-Süd-Einteilung (3 Kategorien)

)


df_analysis <- df_base %>% dplyr::select(
-c(
  BBhh5, 
  BBhh6, 
  IPinfl4_mm,
  IPinfl4_jj,
  SEschwA_zz,
  IAkfutyp5B_lz,
  IAkfutyp7B_lz,
  AUarbzD_k,
  
  BBschwierig4,
  BBschwierig1,
  BBschwierig2,		
  BBschwierig3,			
  BBschwierig5,		
  BBhh4,	
  BBhh7,		
  BBhh1,			
  BBhh2,			
  BBhh3
)
)

df_analysis <- na.omit(df_analysis)

df_analysis <-  df_analysis[complete.cases(df_analysis),]

#df_analysis <- df_analysis %>% mutate_all(factor)

colnames(df_analysis)


```


```{r}
require(randomForest)
# fit=randomForest(factor(GZmehm1)~., data=df_analysis)

library(caret)
library(ranger)
library(tidyverse)

# rf_fit <- train(as.factor(GZmehm1) ~ .,  data = df_analysis, method = "ranger")

```





